# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa318dbf6a351bbc13930fa96c630c4146a7b808a5957ad3529f61a4c4c50ede9ef208e1684b7d65247f8bdd5117fcb08260589e49bd1d98f9cad0baeefceed6

test:
  secret_key_base: b352990e605ab3e896d0f4706e459956f1816b9f314db237aff941b47a5a55ce34a40d1b77a26196c291605f1fc30f9619eaed42d512a6b7cb40972996448bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
